const SUPABASE_URL = "https://iyjryrdsdeaxonwkaeyf.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5anJ5cmRzZGVheG9ud2thZXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMjEzNDcsImV4cCI6MjA5NDY5NzM0N30.5sJ1ahI0UiRbXHBiFqZnfBQlvB07U0dVPA877uMCqXA";

const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);